general.import = [
	"~/.config/alacritty/gruvbox.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"
