# Go to https://alacritty.org/config-alacritty.html for config details
[general]
import=["~/.config/alacritty/rose-pine.toml"]
[window]
decorations="Full"
opacity=1.0
blur=false
[scrolling]
history=3000
[cursor]
vi_mode_style={shape="Block", blinking="Off"}
[font]
size=15
normal={family="JetBrains Mono Nerd Font", style="Regular"}
bold={family="JetBrains Mono Nerd Font", style="Bold"}
italic={family="JetBrains Mono Nerd Font", style="Italic"}
bold_italic={family="JetBrains Mono Nerd Font", style="Bold Italic"}
