[colors.primary]
background="#d9f5ff"
foreground="#566162"

[colors.normal]
black="#e2f8ff"
red="#e73330"
green="#576600"
yellow="#7e5d00"
blue="#1c6da7"
magenta="#d73884"
cyan="#279a91"
white="#737d7e"

[colors.bright]
black="#d9f5ff"
red="#e73330"
green="#576600"
yellow="#7e5d00"
blue="#1c6da7"
magenta="#d73884"
cyan="#279a91"
white="#566162"

[colors.cursor]
text="#d9f5ff"
cursor="#566162"

[colors.vi_mode_cursor]
text="#d9f5ff"
cursor="#566162"

[colors.selection]
background="#40d7fc"
text="#566162"
